version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      # Install dependencies using Composer
      - echo "Installing Composer dependencies"
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - composer global require laravel/installer
  build:
    commands:
      # Debug: Check the contents of the .env file
      - echo "Contents of .env file:"
      - cat .env
      # Get the version from the .env file and replace periods with underscores
      - echo "Getting version from .env file"
      - VERSION=$(grep '^APP_VERSION' .env | cut -d '=' -f2 | sed 's/\./_/g')
      # Debug: Check the value of VERSION
      - echo "Version is: $VERSION"
      # Add additional debugging if the VERSION is empty
      - if [ -z "$VERSION" ]; then echo "VERSION is empty!"; else echo "VERSION is set to: $VERSION"; fi
  post_build:
    commands:
      # Upload the zip file to S3
      - echo "Uploading zip file to S3"
