version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      # Install dependencies using Composer
      - echo "Installing Composer dependencies"
  build:
    commands:
      # Get the version from the .env file and replace periods with underscores
      - echo "Getting version from .env file"\
  post_build:
    commands:
      # Upload the zip file to S3
      - echo "Uploading zip file to S3"
