version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      # Install dependencies using Composer
      - echo "Installing Composer dependencies"
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - composer global require laravel/installer
  build:
    commands:
      # Get the version from the .env file and replace periods with underscores
      - echo "Getting version from .env file"
      - VERSION=$(grep '^APP_VERSION' .env | cut -d '=' -f2 | sed 's/\./_/g')
      # Debug: Check the value of VERSION
      - echo "Version is ci-cd-laravel-$VERSION"
      - composer install --no-dev --optimize-autoloader
      - php artisan config:cache
  post_build:
    commands:
      # Upload the zip file to S3
      - echo "Uploading zip file to S3"
      - VERSION=$(grep '^APP_VERSION' .env | cut -d '=' -f2 | sed 's/\./_/g')
      - zip -r laravel-app-$VERSION.zip . -x .git/\*
      - zip -r laravel-app.zip . -x .git/\*
  artifacts:
    files:
      - laravel-app.zip
